using Li.Lan.Common.Data;
using Li.Lan.Models;
using System;
using System.Linq;
using System.Collections.Generic;

namespace Li.Lan.Data
{
    public interface IDimensionRepository
    {
        IEnumerable<Precinct> SelectPrecincts();

        IEnumerable<string> SelectCities();

        IEnumerable<IssueTag> SelectIssueTags();

        IEnumerable<Candidate> SelectCandidates(short electionId, int? positionId);
    }

    public class DimensionRespository : BaseRepository, IDimensionRepository
    {
        public DimensionRespository(IConnectionStringProvider connectionStringProvider)
            : base(connectionStringProvider)
        {
            // no-op
        }

        public IEnumerable<Precinct> SelectPrecincts()
        {
            IEnumerable<Precinct> result = null;

            using (var ctx = this.CreateContext())
            {
                var query =
                    from p in ctx.Precincts
                    select p;

                result = query.ToList();
            }

            return result;
        }

        public IEnumerable<string> SelectCities()
        {
            // this query was timing out in Azure, optimize for now

            ////IEnumerable<string> result = null;

            ////using (var ctx = this.CreateContext())
            ////{
            ////    var query =
            ////        from p in ctx.Voters
            ////        group p by p.City into g
            ////        select g;

            ////    result = query.Select(x => x.Key).ToList();
            ////}

            ////return result;

            return new[] {
                "ACKLEY",
                "ACKWORTH",
                "ADAIR",
                "ADEL",
                "AFTON",
                "AGENCY",
                "AINSWORTH",
                "AKRON",
                "ALBERT CITY",
                "ALBIA",
                "ALBION",
                "ALBURNETT",
                "ALDEN",
                "ALEXANDER",
                "ALGONA",
                "ALLEMAN",
                "ALLENDORF",
                "ALLERTON",
                "ALLISON",
                "ALPHA",
                "ALTA",
                "ALTA VISTA",
                "ALTON",
                "ALTOONA",
                "ALVORD",
                "AMANA",
                "AMES",
                "ANAMOSA",
                "ANDOVER",
                "ANDREW",
                "ANITA",
                "ANKENY",
                "ANTHON",
                "APLINGTON",
                "ARCADIA",
                "ARCHER",
                "AREDALE",
                "ARGYLE",
                "ARION",
                "ARISPE",
                "ARLINGTON",
                "ARMSTRONG",
                "ARNOLDS PARK",
                "ARTHUR",
                "ASBURY",
                "ASHTON",
                "ASPINWALL",
                "ATALISSA",
                "ATKINS",
                "ATLANTIC",
                "AUBURN",
                "AUDUBON",
                "AURELIA",
                "AURORA",
                "AUSTINVILLE",
                "AVOCA",
                "AYRSHIRE",
                "BADGER",
                "BAGLEY",
                "BALDWIN",
                "BANCROFT",
                "BARNES CITY",
                "BARNUM",
                "BARTLETT",
                "BASSETT",
                "BATAVIA",
                "BATTLE CREEK",
                "BAXTER",
                "BAYARD",
                "BEACON",
                "BEACONSFIELD",
                "BEAMAN",
                "BEAVER",
                "BEDFORD",
                "BELLE PLAINE",
                "BELLEVUE",
                "BELMOND",
                "BENNETT",
                "BENTON",
                "BERNARD",
                "BERWICK",
                "BETTENDORF",
                "BEVINGTON",
                "BIG ROCK",
                "BIGELOW",
                "BIRMINGHAM",
                "BLAIRSBURG",
                "BLAIRSTOWN",
                "BLAKESBURG",
                "BLANCHARD",
                "BLENCOE",
                "BLOCKTON",
                "BLOOMFIELD",
                "BLUE GRASS",
                "BODE",
                "BONAPARTE",
                "BONDURANT",
                "BOONE",
                "BOONEVILLE",
                "BOUTON",
                "BOXHOLM",
                "BOYDEN",
                "BRADDYVILLE",
                "BRADFORD",
                "BRADGATE",
                "BRANDON",
                "BRAYTON",
                "BREDA",
                "BRICELYN",
                "BRIDGEWATER",
                "BRIGHTON",
                "BRISTOW",
                "BRITT",
                "BRONSON",
                "BROOKLYN",
                "BRUNSVILLE",
                "BRYANT",
                "BUCKEYE",
                "BUCKINGHAM",
                "BUFFALO",
                "BUFFALO CENTER",
                "BURLINGTON",
                "BURNSIDE",
                "BURT",
                "BUSSEY",
                "CALAMUS",
                "CALLENDER",
                "CALMAR",
                "CALUMET",
                "CAMANCHE",
                "CAMBRIDGE",
                "CANTON",
                "CANTRIL",
                "CARBON",
                "CARLISLE",
                "CARPENTER",
                "CARROLL",
                "CARSON",
                "CARTER LAKE",
                "CASCADE",
                "CASEY",
                "CASTALIA",
                "CASTANA",
                "CEDAR",
                "CEDAR FALLS",
                "CEDAR RAPIDS",
                "CENTER JUNCTION",
                "CENTER POINT",
                "CENTERVILLE",
                "CENTRAL CITY",
                "CHAPIN",
                "CHARITON",
                "CHARLES CITY",
                "CHARLOTTE",
                "CHARTER OAK",
                "CHATSWORTH",
                "CHELSEA",
                "CHEROKEE",
                "CHESTER",
                "CHILLICOTHE",
                "CHURDAN",
                "CINCINNATI",
                "CLARE",
                "CLARENCE",
                "CLARINDA",
                "CLARION",
                "CLARKSVILLE",
                "CLAYTON",
                "CLEAR LAKE",
                "CLEARFIELD",
                "CLEGHORN",
                "CLEMONS",
                "CLERMONT",
                "CLIMBING HILL",
                "CLINTON",
                "CLIO",
                "CLIVE",
                "CLUTIER",
                "COATSVILLE",
                "COGGON",
                "COIN",
                "COLESBURG",
                "COLFAX",
                "COLLEGE SPRINGS",
                "COLLINS",
                "COLO",
                "COLUMBIA",
                "COLUMBUS CITY",
                "COLUMBUS JCT",
                "COLUMBUS JUNCTION",
                "COLWELL",
                "CONESVILLE",
                "CONRAD",
                "CONROY",
                "COON RAPIDS",
                "COOPER",
                "CORALVILLE",
                "CORNING",
                "CORRECTIONVILLE",
                "CORWITH",
                "CORYDON",
                "COULTER",
                "COUNCIL BLUFFS",
                "CRAIG",
                "CRAWFORDSVILLE",
                "CRESCENT",
                "CRESCO",
                "CRESTON",
                "CROMWELL",
                "CRYSTAL LAKE",
                "CUMBERLAND",
                "CUMMING",
                "CURLEW",
                "CUSHING",
                "CYLINDER",
                "DAKOTA CITY",
                "DALLAS CENTER",
                "DANA",
                "DANBURY",
                "DANVILLE",
                "DAVENPORT",
                "DAVIS CITY",
                "DAWSON",
                "DAYTON",
                "DE SOTO",
                "DECATUR",
                "DECORAH",
                "DEDHAM",
                "DEEP RIVER",
                "DEFIANCE",
                "DELAWARE",
                "DELHI",
                "DELMAR",
                "DELOIT",
                "DELPHOS",
                "DELTA",
                "DENISON",
                "DENMARK",
                "DENVER",
                "DERBY",
                "DES MOINES",
                "DESOTO",
                "DEWAR",
                "DEWITT",
                "DEXTER",
                "DIAGONAL",
                "DICKENS",
                "DIKE",
                "DIXON",
                "DOLLIVER",
                "DONAHUE",
                "DONNAN",
                "DONNELLSON",
                "DOON",
                "DORCHESTER",
                "DOUDS",
                "DOUGHERTY",
                "DOW CITY",
                "DOWS",
                "DRAKESVILLE",
                "DUBUQUE",
                "DUMONT",
                "DUNCOMBE",
                "DUNDEE",
                "DUNKERTON",
                "DUNLAP",
                "DURANGO",
                "DURANT",
                "DYERSVILLE",
                "DYSART",
                "EAGLE GROVE",
                "EARLHAM",
                "EARLING",
                "EARLVILLE",
                "EARLY",
                "EAST AMANA",
                "EDDYVILLE",
                "EDGEWOOD",
                "ELBERON",
                "ELDON",
                "ELDORA",
                "ELDORADO",
                "ELDRIDGE",
                "ELGIN",
                "ELK HORN",
                "ELK RUN HEIGHTS",
                "ELKADER",
                "ELKHART",
                "ELKPORT",
                "ELLIOTT",
                "ELLSTON",
                "ELLSWORTH",
                "ELMA",
                "ELMORE",
                "ELWOOD",
                "ELY",
                "EMERSON",
                "EMMETSBURG",
                "EMMONS",
                "EPWORTH",
                "ESSEX",
                "ESTHERVILLE",
                "EVANSDALE",
                "EVERLY",
                "EXIRA",
                "EXLINE",
                "FAIRBANK",
                "FAIRFAX",
                "FAIRFIELD",
                "FARLEY",
                "FARMERSBURG",
                "FARMINGTON",
                "FARNHAMVILLE",
                "FARRAGUT",
                "FARSON",
                "FAYETTE",
                "FENTON",
                "FERGUSON",
                "FERTILE",
                "FESTINA",
                "FLORIS",
                "FLOYD",
                "FONDA",
                "FONTANELLE",
                "FOREST CITY",
                "FORT DODGE",
                "FOSTORIA",
                "FREDERICKSBURG",
                "FREDERIKA",
                "FREMONT",
                "FRUITLAND",
                "FT ATKINSON",
                "FT CARSON",
                "FT DODGE",
                "FT MADISON",
                "FT RILEY",
                "GALT",
                "GALVA",
                "GARBER",
                "GARDEN CITY",
                "GARDEN GROVE",
                "GARNAVILLO",
                "GARNER",
                "GARRISON",
                "GARWIN",
                "GENEVA",
                "GEORGE",
                "GERMANTOWN",
                "GIBSON",
                "GIFFORD",
                "GILBERT",
                "GILBERTVILLE",
                "GILLETT GROVE",
                "GILMAN",
                "GILMORE CITY",
                "GLADBROOK",
                "GLENWOOD",
                "GLIDDEN",
                "GOLDFIELD",
                "GOODELL",
                "GOOSE LAKE",
                "GOWRIE",
                "GRAETTINGER",
                "GRAFTON",
                "GRAND JUNCTION",
                "GRAND MOUND",
                "GRAND RIVER",
                "GRANDVIEW",
                "GRANGER",
                "GRANT",
                "GRANVILLE",
                "GRAVITY",
                "GRAY",
                "GREELEY",
                "GREEN MOUNTAIN",
                "GREENE",
                "GREENFIELD",
                "GREENVILLE",
                "GRIMES",
                "GRINNELL",
                "GRISWOLD",
                "GRUNDY CENTER",
                "GRUVER",
                "GUERNSEY",
                "GUTHRIE CENTER",
                "GUTTENBERG",
                "HALBUR",
                "HAMBURG",
                "HAMILTON",
                "HAMLIN",
                "HAMPTON",
                "HANCOCK",
                "HANLONTOWN",
                "HANSELL",
                "HARCOURT",
                "HARDY",
                "HARLAN",
                "HARMONY",
                "HARPER",
                "HARPERS FERRY",
                "HARRIS",
                "HARTFORD",
                "HARTLEY",
                "HARTWICK",
                "HARVEY",
                "HASTINGS",
                "HAVELOCK",
                "HAVERHILL",
                "HAWARDEN",
                "HAWKEYE",
                "HAYESVILLE",
                "HAZLETON",
                "HEDRICK",
                "HENDERSON",
                "HEPBURN",
                "HIAWATHA",
                "HIGH AMANA",
                "HIGHLANDVILLE",
                "HILLS",
                "HILLSBORO",
                "HINTON",
                "HOLLAND",
                "HOLSTEIN",
                "HOLY CROSS",
                "HOMESTEAD",
                "HONEY CREEK",
                "HOPKINTON",
                "HORNICK",
                "HOSPERS",
                "HOUGHTON",
                "HUBBARD",
                "HUDSON",
                "HULL",
                "HUMBOLDT",
                "HUMESTON",
                "HUXLEY",
                "IDA GROVE",
                "IMOGENE",
                "INDEPENDENCE",
                "INDIANOLA",
                "INWOOD",
                "IONIA",
                "IOWA CITY",
                "IOWA FALLS",
                "IRA",
                "IRETON",
                "IRWIN",
                "JACKSON JUNCTION",
                "JAMAICA",
                "JANESVILLE",
                "JEFFERSON",
                "JESUP",
                "JEWELL",
                "JOHNSTON",
                "JOICE",
                "JOLLEY",
                "KALONA",
                "KAMRAR",
                "KANAWHA",
                "KELLERTON",
                "KELLEY",
                "KELLOGG",
                "KENSETT",
                "KENT",
                "KEOKUK",
                "KEOSAUQUA",
                "KEOTA",
                "KESLEY",
                "KESWICK",
                "KEYSTONE",
                "KIESTER",
                "KILLDUFF",
                "KIMBALLTON",
                "KINGSLEY",
                "KINROSS",
                "KIRKMAN",
                "KIRKVILLE",
                "KIRON",
                "KLEMME",
                "KNIERIM",
                "KNOXVILLE",
                "LA MOTTE",
                "LA PORTE CITY",
                "LACONA",
                "LADORA",
                "LAKE CITY",
                "LAKE MILLS",
                "LAKE PARK",
                "LAKE VIEW",
                "LAKESIDE",
                "LAKOTA",
                "LAMONI",
                "LAMONT",
                "LAMOTTE",
                "LANESBORO",
                "LANGWORTHY",
                "LANSING",
                "LANYON",
                "LAPORTE CITY",
                "LARCHWOOD",
                "LARRABEE",
                "LATIMER",
                "LAUREL",
                "LAURENS",
                "LAWLER",
                "LAWTON",
                "LE MARS",
                "LECLAIRE",
                "LEDYARD",
                "LEGRAND",
                "LEHIGH",
                "LEIGHTON",
                "LELAND",
                "LENOX",
                "LEON",
                "LESTER",
                "LETTS",
                "LEWIS",
                "LIBERTY CENTER",
                "LIBERTYVILLE",
                "LIDDERDALE",
                "LIME SPRINGS",
                "LINCOLN",
                "LINDEN",
                "LINEVILLE",
                "LINN GROVE",
                "LISBON",
                "LISCOMB",
                "LITTLE CEDAR",
                "LITTLE ROCK",
                "LITTLE SIOUX",
                "LITTLEPORT",
                "LIVERMORE",
                "LOCKRIDGE",
                "LOGAN",
                "LOHRVILLE",
                "LONE ROCK",
                "LONE TREE",
                "LONG GROVE",
                "LORIMOR",
                "LOST NATION",
                "LOVILIA",
                "LOW MOOR",
                "LOWDEN",
                "LUANA",
                "LUCAS",
                "LUTHER",
                "LUVERNE",
                "LUXEMBURG",
                "LUZERNE",
                "LYLE",
                "LYNNVILLE",
                "LYTTON",
                "MACEDONIA",
                "MACKSBURG",
                "MADRID",
                "MAGNOLIA",
                "MALCOM",
                "MALLARD",
                "MALOY",
                "MALVERN",
                "MANCHESTER",
                "MANILLA",
                "MANLY",
                "MANNING",
                "MANSON",
                "MAPLETON",
                "MAQUOKETA",
                "MARATHON",
                "MARBLE ROCK",
                "MARCUS",
                "MARENGO",
                "MARION",
                "MARNE",
                "MARQUETTE",
                "MARSHALLTOWN",
                "MARTELLE",
                "MARTENSDALE",
                "MARTINSBURG",
                "MASON CITY",
                "MASONVILLE",
                "MASSENA",
                "MATLOCK",
                "MAURICE",
                "MAXWELL",
                "MAY CITY",
                "MAYNARD",
                "MAYSVILLE",
                "MCCALLSBURG",
                "MCCAUSLAND",
                "MCCLELLAND",
                "MCGREGOR",
                "MCINTIRE",
                "MECHANICSVILLE",
                "MEDIAPOLIS",
                "MELBOURNE",
                "MELCHER-DALLAS",
                "MELROSE",
                "MELVIN",
                "MENLO",
                "MERIDEN",
                "MERRILL",
                "MESERVEY",
                "MIDDLE",
                "MIDDLE AMANA",
                "MIDDLETOWN",
                "MILES",
                "MILFORD",
                "MILLERSBURG",
                "MILLERTON",
                "MILLVILLE",
                "MILO",
                "MILTON",
                "MINBURN",
                "MINDEN",
                "MINEOLA",
                "MINGO",
                "MISSOURI VALLEY",
                "MITCHELL",
                "MITCHELLVILLE",
                "MODALE",
                "MONDAMIN",
                "MONETA",
                "MONMOUTH",
                "MONONA",
                "MONROE",
                "MONTEZUMA",
                "MONTICELLO",
                "MONTOUR",
                "MONTPELIER",
                "MONTROSE",
                "MOORHEAD",
                "MOORLAND",
                "MORAVIA",
                "MORLEY",
                "MORNING SUN",
                "MORRISON",
                "MOSCOW",
                "MOULTON",
                "MOUNT VERNON",
                "MOVILLE",
                "MT AUBURN",
                "MT AYR",
                "MT ETNA",
                "MT PLEASANT",
                "MT STERLING",
                "MT UNION",
                "MURRAY",
                "MUSCATINE",
                "MYSTIC",
                "NASHUA",
                "NEMAHA",
                "NEOLA",
                "NEVADA",
                "NEW ALBIN",
                "NEW HAMPTON",
                "NEW HARTFORD",
                "NEW LIBERTY",
                "NEW LONDON",
                "NEW MARKET",
                "NEW PROVIDENCE",
                "NEW SHARON",
                "NEW VIENNA",
                "NEW VIRGINIA",
                "NEWBURG",
                "NEWELL",
                "NEWHALL",
                "NEWTON",
                "NICHOLS",
                "NODAWAY",
                "NORA SPRINGS",
                "NORTH BUENA VISTA",
                "NORTH ENGLISH",
                "NORTH LIBERTY",
                "NORTHBORO",
                "NORTHWOOD",
                "NORWALK",
                "NORWAY",
                "NUMA",
                "OAKLAND",
                "OAKVILLE",
                "OCHEYEDAN",
                "ODEBOLT",
                "OELWEIN",
                "OGDEN",
                "OKOBOJI",
                "OLDS",
                "OLIN",
                "OLLIE",
                "ONAWA",
                "ONSLOW",
                "ORAN",
                "ORANGE CITY",
                "ORCHARD",
                "ORIENT",
                "ORLEANS",
                "OSAGE",
                "OSCEOLA",
                "OSKALOOSA",
                "OSSIAN",
                "OTHO",
                "OTLEY",
                "OTO",
                "OTTOSEN",
                "OTTUMWA",
                "OWASA",
                "OXFORD",
                "OXFORD JUNCTION",
                "OYENS",
                "PACIFIC JCT",
                "PACIFIC JUNCTION",
                "PACKWOOD",
                "PALMER",
                "PALO",
                "PANAMA",
                "PANORA",
                "PARKERSBURG",
                "PARNELL",
                "PATON",
                "PATTERSON",
                "PAULLINA",
                "PELLA",
                "PEOSTA",
                "PERCIVAL",
                "PERRY",
                "PERSIA",
                "PERU",
                "PETERSON",
                "PIERSON",
                "PILOT GROVE",
                "PILOT MOUND",
                "PIONEER",
                "PISGAH",
                "PLAINFIELD",
                "PLANO",
                "PLEASANT HILL",
                "PLEASANT VALLEY",
                "PLEASANTVILLE",
                "PLOVER",
                "PLYMOUTH",
                "POCAHONTAS",
                "POLK CITY",
                "POMEROY",
                "POPEJOY",
                "PORTSMOUTH",
                "POSTVILLE",
                "PRAIRIE CITY",
                "PRAIRIEBURG",
                "PRESCOTT",
                "PRESTON",
                "PRIMGHAR",
                "PRINCETON",
                "PROLE",
                "PROMISE CITY",
                "PROTIVIN",
                "PULASKI",
                "QUASQUETON",
                "QUIMBY",
                "RADCLIFFE",
                "RAKE",
                "RALSTON",
                "RANDALIA",
                "RANDALL",
                "RANDOLPH",
                "RATHBUN",
                "RAYMOND",
                "READLYN",
                "REASNOR",
                "RED OAK",
                "REDDING",
                "REDFIELD",
                "REINBECK",
                "REMBRANDT",
                "REMSEN",
                "RENWICK",
                "RHODES",
                "RICEVILLE",
                "RICHLAND",
                "RICKETTS",
                "RIDGEWAY",
                "RINARD",
                "RINGSTED",
                "RIPPEY",
                "RIVERDALE",
                "RIVERSIDE",
                "RIVERTON",
                "ROBINS",
                "ROCK FALLS",
                "ROCK RAPIDS",
                "ROCK VALLEY",
                "ROCKFORD",
                "ROCKWELL",
                "ROCKWELL CITY",
                "RODNEY",
                "ROLAND",
                "ROLFE",
                "ROME",
                "ROSE HILL",
                "ROSSIE",
                "ROWAN",
                "ROWLEY",
                "ROYAL",
                "RUDD",
                "RUNNELLS",
                "RUSSELL",
                "RUTHVEN",
                "RUTLAND",
                "RYAN",
                "SABULA",
                "SAC CITY",
                "SALEM",
                "SALIX",
                "SANBORN",
                "SCARVILLE",
                "SCHALLER",
                "SCHLESWIG",
                "SCOTCH GROVE",
                "SCRANTON",
                "SEARSBORO",
                "SELMA",
                "SERGEANT BLUFF",
                "SEYMOUR",
                "SHAMBAUGH",
                "SHANNON CITY",
                "SHARPSBURG",
                "SHEFFIELD",
                "SHELBY",
                "SHELDAHL",
                "SHELDON",
                "SHELL ROCK",
                "SHELLSBURG",
                "SHENANDOAH",
                "SHERRILL",
                "SIBLEY",
                "SIDNEY",
                "SIGOURNEY",
                "SILVER CITY",
                "SIOUX CENTER",
                "SIOUX CITY",
                "SIOUX RAPIDS",
                "SLATER",
                "SLOAN",
                "SMITHLAND",
                "SOLDIER",
                "SOLON",
                "SOMERS",
                "SOUTH AMANA",
                "SOUTH ENGLISH",
                "SPENCER",
                "SPERRY",
                "SPILLVILLE",
                "SPIRIT LAKE",
                "SPRAGUEVILLE",
                "SPRING HILL",
                "SPRINGBROOK",
                "SPRINGVILLE",
                "ST ANSGAR",
                "ST ANTHONY",
                "ST CHARLES",
                "ST DONATUS",
                "ST LUCAS",
                "ST MARYS",
                "ST OLAF",
                "ST PAUL",
                "STACYVILLE",
                "STAFFORD",
                "STANHOPE",
                "STANLEY",
                "STANTON",
                "STANWOOD",
                "STATE CENTER",
                "STEAMBOAT ROCK",
                "STOCKPORT",
                "STOCKTON",
                "STORM LAKE",
                "STORY CITY",
                "STOUT",
                "STRATFORD",
                "STRAWBERRY POINT",
                "STRUBLE",
                "STUART",
                "SULLY",
                "SUMNER",
                "SUPERIOR",
                "SUTHERLAND",
                "SWALEDALE",
                "SWAN",
                "SWEA CITY",
                "SWEDESBURG",
                "SWISHER",
                "TABOR",
                "TAMA",
                "TEEDS GROVE",
                "TEMPLETON",
                "TENNANT",
                "TERRIL",
                "THAYER",
                "THOMPSON",
                "THOR",
                "THORNBURG",
                "THORNTON",
                "THURMAN",
                "TIFFIN",
                "TINGLEY",
                "TIPTON",
                "TITONKA",
                "TODDVILLE",
                "TOETERVILLE",
                "TOLEDO",
                "TORONTO",
                "TRACY",
                "TRAER",
                "TREYNOR",
                "TRIPOLI",
                "TROY MILLS",
                "TRUESDALE",
                "TRURO",
                "TURIN",
                "UDELL",
                "ULMER",
                "UNDERWOOD",
                "UNION",
                "UNIONVILLE",
                "UNIVERSITY PARK",
                "URBANA",
                "URBANDALE",
                "UTE",
                "VAIL",
                "VALLEY SPRINGS",
                "VAN HORNE",
                "VAN METER",
                "VAN WERT",
                "VARINA",
                "VENTURA",
                "VICTOR",
                "VILLISCA",
                "VINCENT",
                "VINING",
                "VINTON",
                "VOLGA",
                "W DES MOINES",
                "WADENA",
                "WAHPETON",
                "WALCOTT",
                "WALFORD",
                "WALKER",
                "WALL LAKE",
                "WALLINGFORD",
                "WALNUT",
                "WAPELLO",
                "WASHBURN",
                "WASHINGTON",
                "WASHTA",
                "WATERLOO",
                "WATERVILLE",
                "WATKINS",
                "WAUCOMA",
                "WAUKEE",
                "WAUKON",
                "WAVERLY",
                "WAYLAND",
                "WEBB",
                "WEBSTER",
                "WEBSTER CITY",
                "WELDON",
                "WELLMAN",
                "WELLSBURG",
                "WELTON",
                "WESLEY",
                "WEST AMANA",
                "WEST BEND",
                "WEST BRANCH",
                "WEST BURLINGTON",
                "WEST CHESTER",
                "WEST DES MOINES",
                "WEST LIBERTY",
                "WEST OKOBOJI",
                "WEST POINT",
                "WEST UNION",
                "WESTFIELD",
                "WESTGATE",
                "WESTPHALIA",
                "WESTSIDE",
                "WEVER",
                "WHAT CHEER",
                "WHEATLAND",
                "WHITING",
                "WHITTEMORE",
                "WHITTEN",
                "WILLIAMS",
                "WILLIAMSBURG",
                "WILLIAMSON",
                "WILTON",
                "WINDSOR HEIGHTS",
                "WINFIELD",
                "WINTERSET",
                "WINTHROP",
                "WIOTA",
                "WODEN",
                "WOODBINE",
                "WOODBURN",
                "WOODWARD",
                "WOOLSTOCK",
                "WORTHINGTON",
                "WYOMING",
                "YALE",
                "YARMOUTH",
                "YETTER",
                "YORKTOWN",
                "ZEARING",
                "ZWINGLE"
            };

        }

        public IEnumerable<IssueTag> SelectIssueTags()
        {
            IEnumerable<IssueTag> result = null;

            using (var ctx = this.CreateContext())
            {
                var query =
                    from i in ctx.IssueTags
                    select i;

                result = query.ToList();
            }

            return result;
        }

        public IEnumerable<Candidate> SelectCandidates(short electionId, int? positionId)
        {
            IEnumerable<Candidate> result = null;

            using (var ctx = this.CreateContext())
            {
                var query =
                    from c in ctx.Candidates
                    where c.ElectionId == electionId
                    select c;

                if (positionId.HasValue)
                {
                    query = query.Where(x => x.PositionId == positionId.Value);
                }

                result = query.ToList();
            }

            return result;
        }
    }
}